export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description: "Get interview questions and model answers based on your role, experience, and specific focus areas."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description: "Add personal notes to any question and pin important ones to the top – making your learning more organized."
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description: "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic."
  },
  {
    id: "05",
    title: "Simulate Real Interviews",
    description: "Practice with mock interviews that adapt to your answers, providing a realistic preparation experience."
  },
];
